### ISSUE TITLE
jQuery not loaded on local instance 

### ISSUE THREAD

**Issue by beefeater7** [Robbbb/VectorRuler#7]
The preview fails to generate as the settings are being entered. Downloading the file gives an empty vector (with correct dimensions).
![bild](https://user-images.githubusercontent.com/10468970/64920287-4fce3300-d7a5-11e9-9376-cca1b671c1db.png)

Tor browser has the same issue.

**Comment by darigovresearch** [comment]
Recently tried with Firefox and it now appears to render in the browser and the download behaves as it should be.

Think it must have been an old compatibility issue with Firefox but since this posting it had been updated on Firefox's side.

This issue can probably be closed now as it is no longer valid unless @beefeater7 you wish to try again to see if you still have the same issue?

![image](https://user-images.githubusercontent.com/30328618/89706467-dd86b400-d95d-11ea-9757-26683a514665.png)

**Comment by beefeater7** [comment]
Sorry, I didn't investigate this closely. The problem is nothing to do with browsers.

When I found this on GitHub there was no link to [your hosted instance](https://robbbb.github.io/VectorRuler/), therefore I just fetched the repo and ran locally. 

Your instance runs fine. On my machine, the offending line was this: 
https://github.com/Robbbb/VectorRuler/blob/a415535688672b8e879f1b7e8f1994f1a0a3c04b/index.html#L10

The double slash doesn't mesh with `file:///`.

**Comment by beefeater7** [comment]
So it turns out this was [intentional](https://github.com/Robbbb/VectorRuler/pull/2)? 

>This ensures the library is downloaded on clients where mixed content is blocked
-- @l0b0

I don't know if settling on HTTPS is a good compromise, but it is very standard these days. And it solves this issue.

**Comment by JCBerger** [comment]
So should I be downloading this to run it? Is that why I receive:

`Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds.`

**Comment by Robbbb** [comment]
Hi @JCBerger , the main site is fixed now! It should work now. This jquery issue is also solved as far as I know
